version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: python3 main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    env_file: .env
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    env_file:
      - .env
    ports:
      - "5432:5432"
